### PR TITLE
Flush stdout after printing traceback.  

### PR DESCRIPTION
**Pull request by jdieter**
This ensures that we see it if stdout is getting redirected to a log.  I'm using systemd's journal and was missing some log messages without this.

### CODE REVIEW

**Comment by HenriWahl** [comment]
Sounds useful. But doesn't the error appear in the log thanks to the following log.error()? Or do you want the whole traceback? Then it might be a good idea to add sys.stdout.flush() to all occurrences of traceback.

**Comment by jdieter** [comment]
Yes, I'm looking for the whole traceback.  So, yes you're probably right.  Let me send another revision.

**Comment by jdieter** [comment]
You realize that we're importing traceback at the beginning of dhcpy6d, and then we import it again before printing every traceback.  Do you want me to get rid of the initial import or the per-use import?

**Comment by HenriWahl** [comment]
I noticed too - yes, should be enough to import it once at the beginning, so the others might vanish.

**Comment by HenriWahl** [comment]
Thanks again!

**Comment by jdieter** [comment]
No problem.  I hope you don't mind the patches, but I'm trying to get this to fit my usecase of setting a fixed IP for some clients and using an autogenerated IP for any not in the hosts table, and I've run into a things that I'm trying to sort out.

**Comment by HenriWahl** [comment]
Quite the opposite... some more eyes viewing at the code might make it better!
Your scenario should be possible to achieve with dhcpy6d.

**Pull request merged**
